title: Annotate-on documentation
logo: /assets/img/Annotate_on_logo.png
#email: person@address.com
#description: Minimalistic is a theme powered by Jekyll.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

change-lang-label:
  en: Change language
  fr: Changer de langue

content-title:
  en: Content
  fr: Contenu

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Annotate-on/Annotate-on
#  - name: LinkedIn
#    icon: <i class="fa-brands fa-linkedin"></i>
#    link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  en:
    - name: Presentation
      link: ./en/
    - name: Projects
      link: ./en/projects.html

  fr:
    - name: Presentation
      link: ./index.html
      sublist:
      - name: Technologies
        link: ./index.html#technologies
      - name: Installation
        link: ./index.html#installation
    - name: Projets
      link: ./projects.html
      sublist:
      - name: Gestion des projets
        link: ./projects.html#gestion-des-projets

